### ISSUE TITLE
REQUEST: Share Rive Links

### ISSUE THREAD

**Issue by PranayD1807** [phucho2306/RivePullToRefresh#2]
Could you share links to rive files?
So, that we can edit stuff like color the example asset files.

**Comment by phucho236** [comment]
[](https://rive.app/community/8964-17117-pull-to-refresh)

**Comment by phucho2306** [comment]
I'm put all in this link. [https://rive.app/community/files/8964-pull-to-refresh/](https://rive.app/community/files/8964-pull-to-refresh/)
![image](https://github.com/phucho236/RivePullToRefresh/assets/54463698/cc91354e-353b-43d1-8f04-b06fb30ec581)
![image](https://github.com/phucho236/RivePullToRefresh/assets/54463698/66ceb9a6-bcbd-42eb-9bec-5fce1992a01c)

**Comment by PranayD1807** [comment]
Thanks 🎉
